# This file is generated by the Flutter tool. Do not edit it.

def flutter_install_all_ios_pods(ios_application_path = nil)
  flutter_install_ios_plugin_pods(ios_application_path)
end

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  # Path to the root of the Flutter project.
  ios_application_path ||= File.dirname(File.expand_path('..', __FILE__))

  # Get the plugins from the .flutter-plugins file.
  plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  return unless File.exist?(plugins_file)

  require 'json'
  plugins_config = JSON.parse(File.read(plugins_file))
  return unless plugins_config['plugins'] && plugins_config['plugins']['ios']

  plugins_config['plugins']['ios'].each do |plugin|
    name = plugin['name']
    path = plugin['path']
    
    # Check for any .podspec file in darwin, ios, or root
    found_path = nil
    [File.join(path, 'darwin'), File.join(path, 'ios'), path].each do |search_dir|
      if Dir.exist?(search_dir) && !Dir.glob(File.join(search_dir, '*.podspec')).empty?
        found_path = search_dir
        break
      end
    end
    
    pod name, :path => found_path if found_path
  end
end

def flutter_additional_ios_build_settings(target)
  return unless target.respond_to?(:build_configurations)

  target.build_configurations.each do |config|
    # You can add custom build settings here.
  end
end
